### ISSUE TITLE
Maybe return server host/port in the HTTP stats?

### ISSUE THREAD

**Issue by cculianu** [cashshuffle/cashshuffle#13]
https://github.com/cashshuffle/cashshuffle/blob/fdd68f03af3eabc3008f5c16daab44ba88453674/server/stats.go#L23

It might be useful to have the info http server thingie return host/port combo for the cashshuffle protocol service it's associated with.

Rationale: UI-wise it might be easier for users to just remember the host/info port of the shuffle server and "behind the scenes" clients can query the info port to get the real cash shuffle protocol port to connect to.

Was thinking for the EC plugin actually that would eliminate UI noise to have that.

Right now this is what the EC settings screen looks like:

<img width="513" alt="screen shot 2018-12-02 at 11 52 08 pm" src="https://user-images.githubusercontent.com/266627/49345426-56177680-f68d-11e8-9470-2a05c8223f33.png">

^^ It would be REALLY nice to eliminate the need to have the user enter 2 ports... and just have them enter 1 port in the UI (perhaps just the INFO port which would then be queried to discover the other port).

What do you say?

**Comment by zquestz** [comment]
We can easily expose the port, but not the host as it might be behind a NAT and I don't want to introduce that complexity to the stats endpoint. However I think the port is all you need. =)

**Comment by zquestz** [comment]
So I think this should work for you: https://github.com/cashshuffle/cashshuffle/commit/4f2482d301c0665e9b8b813e281052ab306d156e

Just added a new key `shufflePort` so you can get the port you need. You should already have the host. =)

**Comment by cculianu** [comment]
Awesome, thanks man!
