### ISSUE TITLE
Command-line option for server to bind to a specific interface

### ISSUE THREAD

**Issue by cculianu** [cashshuffle/cashshuffle#16]
So that, eg, you can bind *only* to localhost (127.0.0.1).

This allows paranoid tor people and others to not expose the service to the outside world. Right now I think it binds on all interfaces.

**Comment by zquestz** [comment]
This has been fixed in the following commit. https://github.com/cashshuffle/cashshuffle/commit/2953ad9cbc89d10c96df07ae4dde2706c77e62c8

Just pass in `--bind-ip 127.0.0.1` and it will scope it to just the local interface.

**Comment by zquestz** [comment]
Binaries should be available in the 0.3.4 release building now.

**Comment by cculianu** [comment]
Awesome! You rock! 👍
