### ISSUE TITLE
Allow 1 server to bind to 2 stat/shuffle port pairs: 1 pair for SSL, another for non-SSL

### ISSUE THREAD

**Issue by cculianu** [cashshuffle/cashshuffle#17]
... and have the pair actually go to the same place, eg, "see" the same users/traffic/pools.  (This is just the link to the outside that is duplicated, but the internals would be unified).

This allows people to set up a non-SSL .onion tor service (it's hard to get an SSL cert for tor), while also offering a non-tor service that's SSL encrypted -- all with the same user pool.

**Comment by zquestz** [comment]
https://github.com/cashshuffle/cashshuffle/pull/25

**Comment by zquestz** [comment]
Done.

**Comment by cculianu** [comment]
Awesome, thanks man. 👍
