### ISSUE TITLE
Wishlist: Add "ban score" for stats output + protocol version to announce messages

### ISSUE THREAD

**Issue by cculianu** [cashshuffle/cashshuffle#23]
We discussed this in Telegram, @zquestz , but I'm adding it here as a gentle reminder so we both don't forget:

1. "Ban score" added to stats port (shows originating request IP's ban score, if any).
2. Add a "version" field to the announce messages (an int, I guess is fine, or whatever else .. defaulting to 0 or whatever protobuf does when the field is missing on the wire). So pools become defined as `(amount, type, version)` tuples and clients get matched based on those tuples matching.
3. Add the "version" (as well as 'type' if it's not already there?) field to the per-pool dict in the stats/ port output.

Awesome man! You rock!  Thanks so much! 👍

**Comment by zquestz** [comment]
So I have some of this done.

- `banned` and `banScore` are in the json.
- `type` is also in the json.

I will work on the version bit tomorrow after some sleep. =)

**Comment by zquestz** [comment]
I went ahead and implemented version. The server now supports a version field in addition to type. It will create pools based on (amount, type, version) unique sets. 

Also in the stats endpoint it returns the version of each pool.

Let me know if that covers everything.

**Comment by zquestz** [comment]
https://github.com/cashshuffle/cashshuffle/pull/22

**Comment by cculianu** [comment]
And I thought you were going to bed! Ok this looks great.  I can close this now, I think.
