### ISSUE TITLE
unbound pool count

### ISSUE THREAD

**Issue by emergent-reasons** [cashshuffle/cashshuffle#24]
I don't think it would be a meaningful DOS vector but just want to check.

[Here](https://github.com/cashshuffle/cashshuffle/blob/master/server/tracker.go#L138) in the tracker logic, the pool count is unbound.

**Comment by zquestz** [comment]
That is correct. People can create as many pools as is necessary. The server assigns users to them and memory to track a pool is super minimal. If we want to set an upper bound we can, but I don't think it is necessary. Thoughts?

**Comment by emergent-reasons** [comment]
I couldn’t think of a scalable way to attack this with ip filtering enabled
so I don’t think anything is necessary. Just wanted to check. Thanks for
the explanation.

**Comment by zquestz** [comment]
Cool going to close this. The ip restrictions will be in soon. =)
