### ISSUE TITLE
failures on non-TLS servers are silenced

### ISSUE THREAD

**Issue by emergent-reasons** [cashshuffle/cashshuffle#28]
Currently going through to understand mutexes and noticed this.

If the title is right, do you want me to write up a proposal? Maybe bail on server failures and warn on stat server failures?

in `performCommand()`:
```
go server.Start(...)  // failed server will be ignored
go server.Start(...)  // failed server will be ignored
return server.Start(...)  // errors are displayed and the server stops
```

**Comment by zquestz** [comment]
Yep, right now only the main server will actually catch errors. We should probably pass an error channel to all the go routines and collect errors. Would definitely accept a PR for this. =)

**Comment by emergent-reasons** [comment]
Ok! Thanks for the info. Would any of the servers, including a stat server, be grounds for closing down the whole shop?

**Comment by zquestz** [comment]
Yes, we should definitely clean this up and add an error channel to process the errors from goroutines. =)
