### ISSUE TITLE
player can be disconnected for blaming a liar that disconnects

### ISSUE THREAD

**Issue by emergent-reasons** [cashshuffle/cashshuffle#29]
In `banned.go`:

```
		if bannedConnData == nil {
			return errors.New("invalid ban")
		}
```

The return leads to the blaming user being disconnected.

If the liar disconnects quickly, then the above condition can be triggered.

Sorry if I didn't get it exactly right. I think there is an edge case here though.

**Comment by zquestz** [comment]
This is fixed in the latest ban improvement PR.
