### ISSUE TITLE
Shuffle proceed with missing player

### ISSUE THREAD

**Issue by checksum0** [cashshuffle/cashshuffle#3]
- Player 1, 2, and 3 were queued up ready to shuffle.
- Player 4 joins and is queued up.
- Player 1, 2 and 3 unexpectedly leave the queue.
- Player 1 tries to join back the queue and is given Player 2 slot.
- Player 2 tries to join back the queue and is given Player 5 slot - launching the shuffling process.
- Shuffle abort uncleanly as Player 1 and 3 are missing.

I'm unsure if it is an issue on the server or the plugin. Please close if it's a plugin issue and I'll reopen at the correct place.

![error 2](https://user-images.githubusercontent.com/26656348/33952818-f301d246-e000-11e7-84ff-38889084261a.png)

**Comment by zquestz** [comment]
So this shouldn't be a server issue. The server is smart enough to clear out pool spots until the pool is full. Basically it only announces the shuffle if there are enough connected players. Until the pool is full, if a player leaves that slot is opened up and the next player will take that slot.

I am pretty sure this is a plugin bug, but I will do a bit more investigation to double check. =)

**Comment by checksum0** [comment]
I figured out how to enable debug on the server, I can try to reproduce and post the output here...

-------- Original Message --------

**Comment by zquestz** [comment]
Closing as this is most likely a bug in the plugin side. =)
