### ISSUE TITLE
apparent inconsistency on handling/ignoring errors in processReceivedMessage()

### ISSUE THREAD

**Issue by emergent-reasons** [cashshuffle/cashshuffle#30]
[processReceivedMessage()](https://github.com/cashshuffle/cashshuffle/blob/master/server/messages.go#L42)

Although we can't guarantee receipt of messages even if the write succeeds, the behavior looks inconsistent on the surface. There are 3 communications:

1. `pi.announceStart()` internally silences message errors
2. `pi.broadcastJoinedPool()` ignores messaging errors
3. `pi.broadcastMessage()` returns messaging errors

`1.` and `3.` seem intentional. Is there a reason for `2.` to be ignored? It seems that if we know the pool join broadcast failed, it should be handled at least as strictly as the general broadcast?

**Comment by zquestz** [comment]
Actually all of them ignore errors. While `broadcastMessage()`'s method signature can return errors the implementation does not. The errors are all nil just in case the remote end disconnects. Those errors just cause us to broadcast a new round with the remaining players.

**Comment by emergent-reasons** [comment]
I see now. I guess the idea is to leave room for future unrecoverable errors to bubble up a disconnect?

This can be closed, right?
