### ISSUE TITLE
Separate ban parameters with tor clients

### ISSUE THREAD

**Issue by imaginaryusername** [cashshuffle/cashshuffle#33]
Is there a separate class of ban parameters for tor clients yet? I can't see it anywhere. 

If not, if tor clients are banned, due to them all coming from the same source the ban time should be a lot less than 30 minutes - I'll recommend something like 10 minutes, with more ban score (say, 5 instead of 3) before a ban.

**Comment by imaginaryusername** [comment]
Regular clients can also use lowering bantime to 15 minutes to address concerns in #26 - but I'll make a PR for that separately.

**Comment by zquestz** [comment]
PR merged. =)

**Comment by imaginaryusername** [comment]
@gitcash send $1 to @cashshuffle

**Comment by GitCash** [comment]
Hey **cashshuffle**, user **imaginaryusername** tipped you **7874 bits** in Bitcoin Cash ( ~ **$1** ).

*[Click here to claim it!](https://gitcash.io/claim/cashshuffle)*

You can also add the "thumbs down" reaction to **imaginaryusername**'s comment above to prevent future tips.

**Comment by zquestz** [comment]
Seems we can't claim org tips. =(
