### ISSUE TITLE
consider broadcasting new round immediately on detection of a disconnect

### ISSUE THREAD

**Issue by emergent-reasons** [cashshuffle/cashshuffle#43]
The current implementation has this behavior:

- user drops from pool
- server becomes aware of the drop relatively quickly but does not broadcast the new round yet
- when the server attempts to send/relay any message to the dropped user (direct message or broadcast), it ignores the provided message and instead triggers a new round broadcast

It works so far. I noticed some issues though:

- The server happily sends messages between other users without triggering a new round, suggesting that the round is still valid. I don't know how often that happens in the client-side protocol.
- The server sends broadcast messages to *some* players before it hits the disconnected user. When it hits the disconnected user, it stops sending the original message and broadcasts a new round. That could be confusing for clients.

If these are serious / if it could help simplify the spec, then we might consider broadcasting a new round at the time we detect a dropped connection.

**Comment by zquestz** [comment]
Definitely worth investigating but I see some problems with broadcasting the new round as part of the disconnection.

1) Messages already in flight will continue to be relayed, we would introduce a race condition where the new announcement goes out, but other messages from the old round get delivered afterwards!
2) Stopping sending all other messages should not confuse clients, as those messages are not required. The clients should happy accept the new round message which has them clear any internal state about the round.
3) Almost all messages are broadcast messages, so it is VERY rare that a client disconnects and no message gets sent to them.

If we can figure out a nice way to prevent the race condition, then a refactor can happen, but I don't believe this is a launch blocker.

**Comment by emergent-reasons** [comment]
> 1. Messages already in flight will continue to be relayed, we would introduce a race condition where the new announcement goes out, but other messages from the old round get delivered afterwards!

I think this is already an issue in the current implementation (the point that says `The server sends broadcast messages to some players before it hits the disconnected user.`).

> 2. Stopping sending all other messages should not confuse clients, as those messages are not required. The clients should happy accept the new round message which has them clear any internal state about the round.

I think the same thing. Ok no problem there.

> 3. Almost all messages are broadcast messages, so it is VERY rare that a client disconnects and no message gets sent to them.

Cheers. That part is not really an issue then.

**Comment by zquestz** [comment]
> > 1. Messages already in flight will continue to be relayed, we would introduce a race condition where the new announcement goes out, but other messages from the old round get delivered afterwards!
> 
> I think this is already an issue in the current implementation (the point that says `The server sends broadcast messages to some players before it hits the disconnected user.`).
> 

Yes but the messages come in the correct order! The players will receive that message, then it will be followed by the new round. The new round won't happen then get a message from the previous round!

> > 1. Stopping sending all other messages should not confuse clients, as those messages are not required. The clients should happy accept the new round message which has them clear any internal state about the round.
> 
> I think the same thing. Ok no problem there.
> 
> > 1. Almost all messages are broadcast messages, so it is VERY rare that a client disconnects and no message gets sent to them.
> 
> Cheers. That part is not really an issue then.

**Comment by zquestz** [comment]
This is no longer valid. We don't do N-1 rounds anymore, therefore we don't care when we broadcast a new round. In fact, the broadcast new round code can all be removed once the refactor is completed.

**Comment by emergent-reasons** [comment]
Sounds good!

**Comment by emergent-reasons** [comment]
Replaced by #56
