### ISSUE TITLE
SessionID is redundant?

### ISSUE THREAD

**Issue by emergent-reasons** [cashshuffle/cashshuffle#44]
I was going through the logic of validating messages and I do not see any added value of SessionID.

1. It is currently public information, sent in every user->broadcast message. So it cannot be used as a secret.
2. players are uniquely identified by their connection (not IP) when sending a message so the validation of matching sessionid is redundant.

Am I missing something? I think either we should remove session id from the spec or make it a secret value that identifies the player instead of the connection.

**Comment by zquestz** [comment]
the session id is used by the clients. This is part of the official CoinShuffle spec and we should probably keep it for now. The server does not use this data currently, but I like to keep equivalent with the CoinShuffle spec whenever we can.

**Comment by emergent-reasons** [comment]
Sounds like you found sessionID is not used by the client. If it turns out not to be needed by the client, then I see two options:

1. completely factor it out of the protocol, server and clients
2. use it as an anti-connection spoofing mechanism. In this case, it must be reliably cleaned from every message before broadcasting.

Does that sound right?

**Comment by zquestz** [comment]
Yeah, I don't think the spoofing issue is a big one. Since the messages are signed it will be difficult for anyone to insert a bogus message. I think we just refactor it out of the server and client after we discuss with Yura.
