### ISSUE TITLE
Allow occasional disconnects and punish repeated disconnects

### ISSUE THREAD

**Issue by emergent-reasons** [cashshuffle/cashshuffle#46]
Notes from chat:

> When a user disconnects mid shuffle (after pool full and before shuffle completes), then they will earn a disconnect score. When that score is too high, he is isolated from other players from the pool he disconnected from.

It sounds good. What is the cleanest way to implement?

Some issues:

### (server vs p2p) and (immediate vs. score)

- p2p ban is focused and avoids cutting out the whole tor group, but in the case of a score system, it only works for the last victims where the disconnecter finally crosses the line. A misbehaving client likely will affects many more players in the meantime and after.
- a server ban seems almost guaranteed to have the tor group banned continuously.
- I recommend a p2p + immediate pool ban. If you disconnect on an active shuffle, you get banned from the other players immediately. For the common user that is just shutting down their client, this doesn't matter. For a misbehaving client, it quickly isolates the misbehaving client.

### Does the server have any deterministic or even circumstantial way to know the difference between disconnecting before/after shuffle completes?
- I don't think the server knows currently
- The server could snoop on broadcast messages to look for a "vote" of completion - maybe on `BLAME` phase? I am not sure which phases are always broadcast by the clients.
- Even if the server snoops, it still has a race condition where a real player can say everything is done, disconnect -- but the disconnect happens before the complete "vote" is done. That would look like a bad disconnect. Then the server needs to cache the pool users until the pool is fully closed.
- Re "shuffle finished" announcement, as I understand it, that is for when the server detects a clearly failed shuffle condition like blame. If so, it doesn't help to determine when a player can disconnect in good faith.

**Comment by emergent-reasons** [comment]
Re "shuffle finished" announcement, as I understand it, that is for when the server detects a clearly failed shuffle condition like unanimous blame. If so, it doesn't help to determine when a player can disconnect in good faith.

**Comment by emergent-reasons** [comment]
Regarding identifying the end of a shuffle... I started to think that we really shouldn't try. It's all circumstantial anyway. I think it's better to keep an expiring cache of pool-users so that blames coming in after a disconnect can still affect the user. Then we do not need to explicitly track disconnects. Just let the clients handle the blaming.

Note: currently *any* valid blame counts toward the ban vote for a pool. They ban does not require everyone to blame with the same reason.

**Comment by emergent-reasons** [comment]
Do you think the comment I added above will work fine? Just keep a timed cache so that blames can come in within a reasonable time frame and still hit an IP? I'm not sure if zquestz will like it but I will try to get a PR up.

**Comment by emergent-reasons** [comment]
@cculianu @zquestz  I implemented #51 which arguably meets the needs of this issue by letting blame handle misbehaving disconnectors. What do you think?

**Comment by cculianu** [comment]
I think it's needed because right now, as per our discussions, @zquestz .. the clients don't wait around. They blame and disconnect (that can be changed but it adds complexity to do so!).

We need to talk about that -- I'd prefer the clients to just blame and disconnect but I fear perhaps you guys will punish them for disconnecting "uncleanly" after a blame .. will this punishment code kick in for the regular guy that blames-then-disconnects?

**Comment by emergent-reasons** [comment]
There is currently no punishment code for disconnect. I like this blame-based solution because it avoids worrying about disconnect race conditions and avoids judgements about good vs. bad disconnects.

We already have a rate limiter that solves too-many-disconnects by stopping too-many-connects.

**Comment by zquestz** [comment]
Yeah, with the new PR's I think this is taken care of. We now have a snapshot of the pool state, so client don't need to stay around after they blame someone. I also agree with @emergent-reasons that our current blame logic + disconnect rate limits are a good starting point. We can always add more disconnect protections later if we see issues.

**Comment by emergent-reasons** [comment]
@cculianu closing this - I think we are all in agreement.
