### ISSUE TITLE
Explicitly dissolve a pool after shuffle is initiated and it succeeds or has any failure

### ISSUE THREAD

**Issue by emergent-reasons** [cashshuffle/cashshuffle#48]
The discussion consensus seemed to be that making pools predictably short-lived is a better solution than tracking their state and keeping them alive. When it succeeds, the job is done so explicitly end it. When it fails (e.g. a user disconnects after the shuffle has started), then simply dissolve the pool and re-locate the players.

Issues

- Identifying success or failure. See #46 
- Is it necessary to extend the protobuf definition with a new message type? If success/failure detection can be done already, then maybe this is redundant. Just relocate the players and announce as usual?

**Comment by emergent-reasons** [comment]
This is the best I could come up with, but I still don't like it:

1. Ensure that blame messages are only valid after a round has started (I think currently they can arrive at any time?).
2. Always assign blame through a special blame lookup (the frozen pool snapshot) so that we do not need the actual pool around to assign blame. We just need to lookup the pool number --> verification key --> player --> assign blame. (This would be nicer if the pools have UUIDs to avoid funkiness).
3. Now if we can detect an end to the round (sorry I still don't know how to do that), we can freely reassign players. But the problem is by reassigning them ourselves, they suddenly start getting messages that they might not be expecting and did not ask for.

...... 3. makes the whole thing seem like a bad idea unless we actually broadcast an "END" message.

I think I prefer letting the clients decide when they are done or disconnecting them after timeout.

**Comment by zquestz** [comment]
Unfortunately we have no idea if the shuffle has ended. We could add phase tracking per player, and assume a phase has been reached when every player sends messages for that phase. That way we can detect if the shuffle has started and include the phase in the stats endpoint. However, we have no guarantee that the last phase actually completed, as the clients do not send a "shuffle completed" message. =\

**Comment by emergent-reasons** [comment]
Ok that's how I was imagining it. So I think we just close this issue - let players leave whenever they want and the expectation is that a new round will never start. I believe the current EC implementation does that already - as soon as it finishes or blames, the client drops. Is that correct @cculianu ?

**Comment by zquestz** [comment]
Yep agreed.
