### ISSUE TITLE
consider using a consistent and invariant lookup / id mechanism for users

### ISSUE THREAD

**Issue by emergent-reasons** [cashshuffle/cashshuffle#55]
I suspect there are still some devious issues hiding in the different player lookup methods.

Since we are enforcing a unique verification key from #47 and that is the value that other players also know, my first thought is that we should use vk as the unified lookup.

I may try this some time to see how it looks. If anyone has an opinion, please post.

**Comment by emergent-reasons** [comment]
If I remember correctly, the connection is the least-spoofable identification we have so it may be that Josh set everything up exactly right already.

**Comment by zquestz** [comment]
I think the current logic is the best way to move forward. That way validation of the data is super easy. Going to close this one. Unless someone feels strongly about another key then I think we are good as is.
