### ISSUE TITLE
simplify banning and broadcast logic

### ISSUE THREAD

**Issue by emergent-reasons** [cashshuffle/cashshuffle#57]
1. actually remove player when they are banned from a pool. this simplifies broadcast testing
2. iterate over the players in the pool rather than all connections on the tracker when making a broadcast.

@zquestz I feel like there might be a reason that we didn't do 1. already but I can't think of it. Any problem with removing players immediately on ban?

**Comment by emergent-reasons** [comment]
E.g. in  `announceStart`

**Comment by zquestz** [comment]
We can do that now that we track disconnected users.

**Comment by emergent-reasons** [comment]
> We can do that now that we track disconnected users.

Right! I had already internalized that change. Ok I can put up a PR for this at some point.

**Comment by emergent-reasons** [comment]
I think changing the broadcast signature would fit fine here as well.

**Comment by zquestz** [comment]
Sounds great. =)
