### ISSUE TITLE
fix: passive players will cause a shuffle timeout and be unblameable

### ISSUE THREAD

**Issue by emergent-reasons** [cashshuffle/cashshuffle#59]
If I understand correctly, the server and other players are vulnerable to a passive player:

Does this logic hold?
- User registers and sends no more messages.
- Their pool will eventually fill up and shift to phase 1
- The other players announce and do whatever
- Eventually the shuffle times out because passive player never does anything
- The other players cannot blame passive player because they still do not know the verification key

If that is correct, we should probably do something to either ban them on the server side or give the other players the vk so they can ban.

**Comment by zquestz** [comment]
Yep this is a known issue, we should really think about good ways to mitigate this.

**Comment by emergent-reasons** [comment]
The simplest and least leaky thing I could think of is to just flag each user as silent until they speak up (after registration and after pool freeze). If they are still flagged as silent when they get removed, it's worth a +1 on the ban score.

Might be a more elegant way without additional data though?

**Comment by zquestz** [comment]
I think this makes perfect sense. Does mean we need to track more data, but I think that is fine. Also we might want to bump the ban score AND isolate via IP deny.

**Comment by emergent-reasons** [comment]
Yeah I edited my comment about p2p too :D
I can PR this at some point also.

**Comment by emergent-reasons** [comment]
@zquestz Would it be terrible to allow blame through player number? If we allow multiple rounds, it is probably not a great idea but with a single round, it's all fixed at phase 1.

**Comment by zquestz** [comment]
I prefer not to do the number, it makes automated attacks much easier. You can just setup a bot to connect to a pool then blame all the predictable player numbers. With the verification key at least they need to start the round before blaming people. The scripts to screw things up based on blames by player number are just significantly easier to write...
