### ISSUE TITLE
fix: race condition in ban/voting logic

### ISSUE THREAD

**Issue by emergent-reasons** [cashshuffle/cashshuffle#60]
It's a somewhat pathological case, but there is a race condition on blame/voting.

Consider 3 honest players and 2 independent dishonest players.

- d0 blames d1. (nothing happens)
- 3 honest players blame d0 (nothing happens)
- 3 honest players blame d1 (d1 is banned)
- ... d0 does not get banned (because of the race condition with who gets banned first)

Since we are freezing pools, I recommend we do the following:

- track all ban messages
- When any player hits the voting threshold, we silence them and reduce the voters as before. ***However we still listen to their blames***. 
- When the voting threshold decreases, we check all the players against the new threshold.

It would be simpler to wait until the end and do everything at once but with the above process, we get iterative banning without the race condition.

@zquestz, if you are ok with that, I will include it in the PR I will do for #57

**Comment by zquestz** [comment]
I think this is low priority. Don't mind it being fixed, but I think logically it only makes sense to allow for 1 ban per round. Otherwise if there are many malicious peers then they can gang up and ban several people per round and cause some chaos.

**Comment by emergent-reasons** [comment]
Fine with me. In that case.... would you say it is valid to codify 1-ban-per-round ? That would let us solve this problem and also simplify the code.

**Comment by zquestz** [comment]
Yep I think that is totally fine =)
