### ISSUE TITLE
Thought of a quick n' dirty fix to the "race condition" 

### ISSUE THREAD

**Issue by cculianu** [cashshuffle/cashshuffle#63]
As per our discussion today, @zquestz, if in fact clients timing out just as the announcement message arrives when the pool fills is indeed the culprit, a server-side workaround could be:

- If the client was around for say at least 50-55 seconds in the pool, and he disconnects after that time, then you can assume he may have just timed out. In that case don't apply any penalty.

This is a compromise position and an attacker could still get away with sabotaging a pool by disconnecting right after announce -- but to do it without penalty he also has to wait around in a pool that didn't fill for 55 seconds.. so it definitely mitigates the attacks they can pull off -- while still allowing wiggle room for the odd unfortunate client that just didn't get the message in time.

What do you think?

**Comment by cculianu** [comment]
Just to confirm the client *does* reset its idle timer when it sees activity like "another player joined the pool" message.  But those messages do arrive one after another anyway right? (eg last player joins + pool full announce) and the client was already at 60.0 seconds ... then maybe race condition ?

This definitely needs some investigation. 

Just adding this here so we have a record of the discussion outside of telegram, which is somewhat ephemeral.

**Comment by zquestz** [comment]
I have added additional logging in the latest build. Want to see a more clear picture of what is occurring before making adjustments. =)

**Comment by cculianu** [comment]
This also looks like a likely suspect: https://github.com/cashshuffle/cashshuffle/blob/566547a262cdee913a31d808b6a1519bb823d35c/cmd/main.go#L145

I noticed what logging you added.  It's a good start.  At the risk of sounding like a real stichler -- you also need to log when it makes a deny decision, etc, and also log the timer value (so we can see if there are logic errors in the cleanup code).

But yeah it's a good start.

Thanks man.

**Comment by zquestz** [comment]
Going to close this. I think removing the denyIP for the passive case was the right move. We still add to the ban score so we do offer protection from this case anyways. Pools have been super stable all day. =)

**Comment by cculianu** [comment]
Agreed. Close it.  :)
