### ISSUE TITLE
Make sure player receives all blame messages before being kicked

### ISSUE THREAD

**Issue by emergent-reasons** [cashshuffle/cashshuffle#72]
For non-malicious clients, it will be good to receive feedback so they can improve the client.

For malicious clients, they can look at the source code anyway so nothing new is being revealed.

Alternatives:

- don't kick players on ban and then they will receive the messages

**Comment by zquestz** [comment]
We don't actually disconnect them... we do remove them from the pool, but no where in the code do we disconnect a banned client.

**Comment by emergent-reasons** [comment]
> We don't actually disconnect them... we do remove them from the pool, but no where in the code do we disconnect a banned client.

That's right. I should have been more specific than "kick". We remove their vk and connection from the lookup tables so the normal code paths consider the player non-existent. That includes the message sending code. Their connection does persist and is tracked in the frozen snapshot but that is only used for internal lookups with blame.

The way it is currently, the accused will receive 1, 2, ... N-2 blames but will not receive the N-1 blame.

I added that `remove(accused)` but I don't see a great reason for it now unless we assume they are spamming messages or some other bad behavior. Just deleting the `remove(accused)` would solve this and I do not immediately see negative side effects.
