### ISSUE TITLE
message.proto in client and server differ

### ISSUE THREAD

**Issue by MaxXor** [cashshuffle/cashshuffle#8]
Shouldn't these files be the same?
https://github.com/cashshuffle/cashshuffle-electron-cash-plugin/blob/9785a6d904e4b1ef4d7498d916c5e0aa38663f51/protobuf/message.proto#L11-L12
https://github.com/cashshuffle/cashshuffle/blob/1440c6ea4dd1e02793e7e547cca2464f22c1db2b/message/message.proto#L11-L12

**Comment by zquestz** [comment]
This is fixed in https://github.com/cashshuffle/cashshuffle/commit/6e00d5f8e30158e4f1479325e3eb3feb6d1d2495

Strange that it was working. Probably because the encoded type was identical. Either way you are right and they should be identical. =)

**Comment by MaxXor** [comment]
Np, just found it out by coding my own server implementation, here: https://github.com/MaxXor/CashShuffle :D

**Comment by zquestz** [comment]
Nice, always good to have multiple options. If you have any questions let me know. =)
